apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-store
  namespace: dev-app
  labels:
    app: store
    environment : dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: aramidhwan/store:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: dev-app-secret
                  key: db_url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dev-app-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-app-secret
                  key: db_password
            - name: KAFKA-BINDER-BROKERS
              valueFrom:
                configMapKeyRef:
                  name: dev-app-configmap
                  key: kafka_binder_brokers
---
apiVersion: v1
kind: Service
metadata:
  name: dev-store
  namespace: dev-app
  labels:
    app: store
    environment : dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: store
#  type: ClusterIP
#  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: dev-store-headless-svc
  namespace: dev-ingress
spec:
  # {Service Name}.{Namespace}.svc.cluster.local 형식으로 작성
  externalName: dev-store.dev-app.svc.cluster.local
  selector:
    app: store
  type: ExternalName
