apiVersion: v1
kind: Service
metadata:
  name: dev-store
  namespace: dev-app
  labels:
    app: store
    environment : dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: store
#  type: ClusterIP
#  type: LoadBalancer
