server:
  port: 8443
#  port: 81

spring:
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
  #      settings:
  #        web-allow-others: true
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin
    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
#      username: admin
#      password: admin
      maximum-pool-size: 10 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기
      connectionTimeout: 2000   # ms, 기본값(30000), 최소값(250ms)
#      idle-timeout: 600000 #연결 위한 최대 유후 시간
#      maxLifetime: 1800000 # Default: 1800000 (30 minutes), 반납된 커넥션의 최대 수명, 0이면 무한.

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092 #, localhost:9093, localhost:9094

    openfeign:
      client:
        config:
          ORDER:        # @FeignClient(name="ORDER")에 해당하는 부분 기술
            url: https://my-pizza.io:90/order-service

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://admin:admin@localhost:7761/eureka    #유레카 서버 주소 http://아이디:비밀번호@아이피:8761/eureka

mypizza:
  cors:
    allowedOrigins: https://my-pizza.io:90, https://my-pizza.io:9090, https://39.118.150.37:9090