apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-mypage
  namespace: dev-app
  labels:
    app: mypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypage
  template:
    metadata:
      labels:
        app: mypage
    spec:
      containers:
        - name: mypage
          image: aramidhwan/mypage:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: dev-app-secret
                  key: db_url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dev-app-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-app-secret
                  key: db_password
            - name: KAFKA-BINDER-BROKERS
              valueFrom:
                configMapKeyRef:
                  name: dev-app-configmap
                  key: kafka_binder_brokers
            - name: FEIGN-URL-STORE-SERVICE
              valueFrom:
                configMapKeyRef:
                  name: dev-app-configmap
                  key: feign-url-store-service