apiVersion: v1
kind: Service
metadata:
  name: dev-customercenter
  namespace: dev-app
  labels:
    app: customercenter
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: customercenter
#  type: ClusterIP
#  type: LoadBalancer
