server:
#  port: 82
  port: 8442
  ssl:
    enabled: true
    key-store: src/main/resources/mypizza.p12
    #    key-store: classpath:mypizza.p12     # classpath: 가 src/main/resources 와 동일한 의미임
    key-store-password: shin22
    key-store-type: PKCS12
    key-alias: mypizza

spring:
  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기
      # 1. 커넥션 유효성 검증 쿼리 설정 (DB 종류에 맞게 설정)
      connection-test-query: SELECT 1   # mySQL
      # 2. 유휴(Idle) 커넥션을 점검할 주기 설정 (ms, DB 타임아웃보다 짧게, 최소가 30초??)
      keepalive-time: 10000
      # 3. 검증 쿼리의 최대 타임아웃 설정 (기본값 5초)
      validation-timeout: 1000
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092     #, localhost:9093, localhost:9094

    openfeign:
      client:
        config:
          GATEWAY:        # @FeignClient(name="STORE")에 해당하는 부분 기술
            url: https://my-pizza.io

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://admin:admin@localhost:7761/eureka    #유레카 서버 주소 http://아이디:비밀번호@아이피:8761/eureka
