apiVersion: v1
kind: Service
metadata:
  name: dev-common
  namespace: dev-app
  labels:
    app: common
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: common
#  type: ClusterIP
#  type: LoadBalancer
