server:
  port: 8080

spring:
  application:
    name: gateway

  #  config:
  #    active:
  #      on-profile: local

  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true

      routes:
        - id: store
          uri: http://dev-store.dev-app.svc.cluster.local:8080
          # Service 개체가 ClusterIP 일때는 동일 네임스페이스 내에서는 단순히 http://dev-store:8080 만으로도 호출 가능
          # uri: http://dev-store:8080 ← 단, gateway가 같은 dev-app 네임스페이스에 있을 때만 가능
          predicates:
            - Path=/store-service/**
          filters:
            - RewritePath=/store-service/(?<segment>.*), /$\{segment}
        #            - name: JwtAuthentication # 적용할 필터 팩토리이름
        - id: order
          uri: https://order:80   # 단일 포트
          #          uri: lb://ORDER       # 멀티 포트, EUREKA 서버 모니터링 페이지에 표시된 Application 명칭
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        #            - name: JwtAuthentication # 적용할 필터 팩토리이름
        - id: delivery
          uri: http://dev-delivery.:80   # 단일 포트
          #          uri: lb://BOARD       # 멀티 포트, EUREKA 서버 모니터링 페이지에 표시된 Application 명칭
          predicates:
            - Path=/delivery-service/**
          filters:
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}
        #            - name: JwtAuthentication # 적용할 필터 팩토리이름
        - id: mypage
          uri: https://mypage:80   # 단일 포트
          #          uri: lb://BOARD       # 멀티 포트, EUREKA 서버 모니터링 페이지에 표시된 Application 명칭
          predicates:
            - Path=/mypage-service/**
          filters:
            - RewritePath=/mypage-service/(?<segment>.*), /$\{segment}
        #            - name: JwtAuthentication # 적용할 필터 팩토리이름
        - id: root
          uri: https://common:80
          predicates:
            #            - Path=/**   # --> 요거는 '/'를 포함하지 않음
            - Path=/
        - id: ignore-favicon
          uri: http://localhost  # 아무거나, 실제 요청 안 함
          predicates:
            - Path=/favicon.ico
          filters:
            - SetStatus=204
        - id: common
          uri: https://common:80   # 단일 포트
          #          uri: http://localhost:85   # 단일 포트
          #          uri: lb://COMMON       # 멀티 포트, EUREKA 서버 모니터링 페이지에 표시된 Application 명칭
          predicates:
            - Path=/common-service/**
          #            - Path=/**   # --> 요거는 '/'를 포함하지 않음
          #            - Path=/
          filters:
            - RewritePath=/common-service/(?<segment>.*), /$\{segment}
        #            - RewritePath=/(?<segment>.*), /$\{segment}
        #            - name: JwtAuthentication # 적용할 필터 팩토리이름
        #              args: # Config 클래스에 사용할 멤버변수 정의
        #                granted: Bearer

  data:
    redis:
      #      url: redis://default:5ZpXqxXLhYmcNfwPElUUAypbIvyecML6@redis-13136.c53.west-us.azure.redns.redis-cloud.com:13136
      host: redis-13136.c53.west-us.azure.redns.redis-cloud.com
      port: 13136
      #      username: default
      password: 5ZpXqxXLhYmcNfwPElUUAypbIvyecML6
#      ssl:
#        enabled: true
#      lettuce:
#        pool:
#          enabled: true   # commons-pool2 디펜던시를 추가해야 한다
#          max-active: 30
#          max-idle: 30
#          min-idle: 30  # 이 설정은 time-between-eviction-runs 설정 시간이 양수인 경우에 적용됨.
#          time-between-eviction-runs: 60  # 제거 스레드의 실행 시간 주기 설정. 음수 값이 지정된 경우 제거 스레드를 실행되지 않음.제거 스레드를 통해서 min-idle, max-idle 에 설정된 수치를 넘어선 경우 불필요한 idle connection을 제거하여 리소스를 효율적으로 관리함.

management:                 # Spring Actuator
  endpoint:
    gateway:
      enabled: true         # default: true
  endpoints:
    web:
      exposure:
        include: gateway,env    # 엔드포인트가 어떤 항목들을 사용할 것인지 지정 (여기서는 gateway)
#        include: gateway,health    # 엔드포인트가 어떤 항목들을 사용할 것인지 지정
#        exclude: metrics

mypizza:
  domain:
    redirect:
      enabled: false