server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기

  cloud:
    config:
      enabled: false
    stream:
      kafka:
        binder:
          brokers: ${KAFKA-BINDER-BROKERS}

    openfeign:
      client:
        config:
          GATEWAY:        # @FeignClient(name="STORE")에 해당하는 부분 기술
            url: ${FEIGN-URL-GATEWAY-SERVICE}

eureka:
  client:
    enabled: false