apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-mysql
  namespace: dev-db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-db-secret
#                  name: dev-secret-headless-svc
                  key: mysql-root-password
            - name: TZ
              value: "Asia/Seoul"
