apiVersion: v1
kind: Secret
metadata:
  name: dev-app-secret
  namespace: dev-app
type: Opaque
stringData:
  db_url: jdbc:mysql://dev-mysql-headless-svc:3306/my-pizza?create=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
data:
# 아래 명령어로 base64로 encoding한 문자열을 넣는다.
# echo -n "문자열" | base64
#  db_url: jdbc:mysql://mypizzadb.mysql.database.azure.com:3306/my-pizza?create=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
#  db_url: >
#    amRiYzpteXNxbDovL215cGl6emFkYi5teXNxbC5kYXRhYmFzZS5henVyZS5jb206MzMwNi9teS1w
#    aXp6YT9jcmVhdGU9dHJ1ZSZ1c2VTU0w9ZmFsc2UmYWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1
#    ZSZjaGFyYWN0ZXJFbmNvZGluZz1VVEYtOA==
  db_username: YWRtaW4=
#  db_username: YWRtaW5AbXlwaXp6YWRiLm15c3FsLmRhdGFiYXNlLmF6dXJlLmNvbQ==
#  db_username: "admin@mypizzadb.mysql.database.azure.com"
  db_password: YWRtaW4=

#  db_url: jdbc:mysql://mypizzadb.mysql.database.azure.com:3306/my-pizza?create=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
#  db_username: "admin@mypizzadb.mysql.database.azure.com"
#  db_password: "admin"
#  mysql-root-password: "shin22"
#  kafka_binder_brokers: dev-kafka-service:9092
