server:
  port: 8441
#  port: 85
  ssl:
    enabled: true
    #    key-store: src/main/resources/mypizza.p12
    key-store: classpath:mypizza.p12     # classpath: 가 src/main/resources 와 동일한 의미임0x
    key-store-password: shin22
    key-store-type: PKCS12
    key-alias: mypizza

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin
    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
#      username: admin
#      password: admin
      maximum-pool-size: 13 #최대 pool 크기
      minimum-idle: 13 #최소 pool 크기
      connectionTimeout: 2000   # ms, 기본값(30000), 최소값(250ms)
#      idle-timeout: 600000 #연결 위한 최대 유후 시간
#      maxLifetime: 1800000 # Default: 1800000 (30 minutes), 반납된 커넥션의 최대 수명, 0이면 무한.

      # 1. 커넥션 유효성 검증 쿼리 설정 (DB 종류에 맞게 설정)
      connection-test-query: SELECT 1   # mySQL
      # 2. 유휴(Idle) 커넥션을 점검할 주기 설정 (ms, DB 타임아웃보다 짧게)
      keepalive-time: 30000
      # 3. 검증 쿼리의 최대 타임아웃 설정 (기본값 5초)
      validation-timeout: 1000
  data:
    redis:
      # https://redis.io/ 접속
      # Log in > 구글 로그인 aramidhwan@gmail.com
      # Try Free 선택하고 "Create Database" 한 후 "Connect" 클릭, id는 default, password는 Jedis 선택한 후 눈표시 아이콘 클릭하면 보임
      host: redis-15347.c53.west-us.azure.cloud.redislabs.com
      port: 15347
      username: default
      password: pXl9nElgxkcsx4gAiLRLBRttxZVsYkZb
#      ssl:
#        enabled: true
#      lettuce:
#        pool:
#          enabled: true   # commons-pool2 디펜던시를 추가해야 한다
#          max-active: 30
#          max-idle: 30
#          min-idle: 30  # 이 설정은 time-between-eviction-runs 설정 시간이 양수인 경우에 적용됨.
#          time-between-eviction-runs: 60  # 제거 스레드의 실행 시간 주기 설정. 음수 값이 지정된 경우 제거 스레드를 실행되지 않음.제거 스레드를 통해서 min-idle, max-idle 에 설정된 수치를 넘어선 경우 불필요한 idle connection을 제거하여 리소스를 효율적으로 관리함.

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://admin:admin@localhost:7761/eureka    #유레카 서버 주소 http://아이디:비밀번호@아이피:8761/eureka
