server:
  port: 443
#  port: 85

spring:
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
  #      settings:
  #        web-allow-others: true
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기

  data:
    redis:
      host: redis-13136.c53.west-us.azure.redns.redis-cloud.com
      port: 13136
#      username: default
      password: 5ZpXqxXLhYmcNfwPElUUAypbIvyecML6
#      ssl:
#        enabled: true
#      lettuce:
#        pool:
#          enabled: true   # commons-pool2 디펜던시를 추가해야 한다
#          max-active: 30
#          max-idle: 30
#          min-idle: 30  # 이 설정은 time-between-eviction-runs 설정 시간이 양수인 경우에 적용됨.
#          time-between-eviction-runs: 60  # 제거 스레드의 실행 시간 주기 설정. 음수 값이 지정된 경우 제거 스레드를 실행되지 않음.제거 스레드를 통해서 min-idle, max-idle 에 설정된 수치를 넘어선 경우 불필요한 idle connection을 제거하여 리소스를 효율적으로 관리함.

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://admin:admin@localhost:7761/eureka    #유레카 서버 주소 http://아이디:비밀번호@아이피:8761/eureka

mypizza:
  cors:
    allowedOrigins: https://my-pizza.io