server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/my-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기

  cloud:
    stream:
      kafka:
        binder:
          brokers: INTERNAL://kafka-1:19092, INTERNAL://kafka-2:19093, INTERNAL://kafka-3:19094

    openfeign:
      client:
        config:
          STORE:        # @FeignClient(name="STORE")에 해당하는 부분 기술
#   FeignClient 이름(name)을 Eureka 서버에 등록된 상대 클라이언트 이름(spring.application.name)으로 지정하면
#   해당 이름을 가진 Eureka 클라이언트에게 API 요청을 수행한다.
#   이렇게 Eureka 클라이언트 이름을 사용하면 ""별도의 URL 정보가 필요 없다"".
#            url: http://my-pizza.io/store-service/

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@eurekaserver:8761/eureka    #??? ?? ?? http://???:????@???:8761/eureka